package za.co.WebServices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.3
 * 2025-08-26T12:12:00.388+02:00
 * Generated source version: 4.1.3
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "INIWS_NIF")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.ObjectFactory.class, ObjectFactory.class})
public interface INIWSNIF {

    @WebMethod(operationName = "RetrieveUnauthorisedBatches", action = "http://tempuri.org/INIWS_NIF/RetrieveUnauthorisedBatches")
    @Action(input = "http://tempuri.org/INIWS_NIF/RetrieveUnauthorisedBatches", output = "http://tempuri.org/INIWS_NIF/RetrieveUnauthorisedBatchesResponse")
    @RequestWrapper(localName = "RetrieveUnauthorisedBatches", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveUnauthorisedBatches")
    @ResponseWrapper(localName = "RetrieveUnauthorisedBatchesResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveUnauthorisedBatchesResponse")
    @WebResult(name = "RetrieveUnauthorisedBatchesResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String retrieveUnauthorisedBatches(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey
    );

    @WebMethod(operationName = "AccountFundsRelease", action = "http://tempuri.org/INIWS_NIF/AccountFundsRelease")
    @Action(input = "http://tempuri.org/INIWS_NIF/AccountFundsRelease", output = "http://tempuri.org/INIWS_NIF/AccountFundsReleaseResponse")
    @RequestWrapper(localName = "AccountFundsRelease", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.AccountFundsRelease")
    @ResponseWrapper(localName = "AccountFundsReleaseResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.AccountFundsReleaseResponse")
    @WebResult(name = "AccountFundsReleaseResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String accountFundsRelease(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "Date", targetNamespace = "http://tempuri.org/")
        java.lang.String date,
        @WebParam(name = "AmountInCents", targetNamespace = "http://tempuri.org/")
        java.lang.Long amountInCents
    );

    @WebMethod(operationName = "RetrieveTransactionTypes", action = "http://tempuri.org/INIWS_NIF/RetrieveTransactionTypes")
    @Action(input = "http://tempuri.org/INIWS_NIF/RetrieveTransactionTypes", output = "http://tempuri.org/INIWS_NIF/RetrieveTransactionTypesResponse")
    @RequestWrapper(localName = "RetrieveTransactionTypes", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveTransactionTypes")
    @ResponseWrapper(localName = "RetrieveTransactionTypesResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveTransactionTypesResponse")
    @WebResult(name = "RetrieveTransactionTypesResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String retrieveTransactionTypes(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "PollingId", targetNamespace = "http://tempuri.org/")
        java.lang.String pollingId
    );

    @WebMethod(operationName = "RequestTransactionTypes", action = "http://tempuri.org/INIWS_NIF/RequestTransactionTypes")
    @Action(input = "http://tempuri.org/INIWS_NIF/RequestTransactionTypes", output = "http://tempuri.org/INIWS_NIF/RequestTransactionTypesResponse")
    @RequestWrapper(localName = "RequestTransactionTypes", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestTransactionTypes")
    @ResponseWrapper(localName = "RequestTransactionTypesResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestTransactionTypesResponse")
    @WebResult(name = "RequestTransactionTypesResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String requestTransactionTypes(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey
    );

    @WebMethod(operationName = "RetrieveProofOfPayment", action = "http://tempuri.org/INIWS_NIF/RetrieveProofOfPayment")
    @Action(input = "http://tempuri.org/INIWS_NIF/RetrieveProofOfPayment", output = "http://tempuri.org/INIWS_NIF/RetrieveProofOfPaymentResponse")
    @RequestWrapper(localName = "RetrieveProofOfPayment", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveProofOfPayment")
    @ResponseWrapper(localName = "RetrieveProofOfPaymentResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveProofOfPaymentResponse")
    @WebResult(name = "RetrieveProofOfPaymentResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.RetrieveProofOfPaymentResponse retrieveProofOfPayment(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "TransactionId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer transactionId
    );

    @WebMethod(operationName = "RequestPresentationDate", action = "http://tempuri.org/INIWS_NIF/RequestPresentationDate")
    @Action(input = "http://tempuri.org/INIWS_NIF/RequestPresentationDate", output = "http://tempuri.org/INIWS_NIF/RequestPresentationDateResponse")
    @RequestWrapper(localName = "RequestPresentationDate", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestPresentationDate")
    @ResponseWrapper(localName = "RequestPresentationDateResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestPresentationDateResponse")
    @WebResult(name = "RequestPresentationDateResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String requestPresentationDate(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "Date", targetNamespace = "http://tempuri.org/")
        java.lang.String date,
        @WebParam(name = "Instruction", targetNamespace = "http://tempuri.org/")
        java.lang.String instruction,
        @WebParam(name = "ForwardActionDate", targetNamespace = "http://tempuri.org/")
        java.lang.String forwardActionDate
    );

    @WebMethod(operationName = "RetrieveSpecificBatchStatus", action = "http://tempuri.org/INIWS_NIF/RetrieveSpecificBatchStatus")
    @Action(input = "http://tempuri.org/INIWS_NIF/RetrieveSpecificBatchStatus", output = "http://tempuri.org/INIWS_NIF/RetrieveSpecificBatchStatusResponse")
    @RequestWrapper(localName = "RetrieveSpecificBatchStatus", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveSpecificBatchStatus")
    @ResponseWrapper(localName = "RetrieveSpecificBatchStatusResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveSpecificBatchStatusResponse")
    @WebResult(name = "RetrieveSpecificBatchStatusResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String retrieveSpecificBatchStatus(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "BatchName", targetNamespace = "http://tempuri.org/")
        java.lang.String batchName
    );

    @WebMethod(operationName = "AccountServiceKeys", action = "http://tempuri.org/INIWS_NIF/AccountServiceKeys")
    @Action(input = "http://tempuri.org/INIWS_NIF/AccountServiceKeys", output = "http://tempuri.org/INIWS_NIF/AccountServiceKeysResponse")
    @RequestWrapper(localName = "AccountServiceKeys", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.AccountServiceKeys")
    @ResponseWrapper(localName = "AccountServiceKeysResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.AccountServiceKeysResponse")
    @WebResult(name = "AccountServiceKeysResult", targetNamespace = "http://tempuri.org/")
    public com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring accountServiceKeys(

        @WebParam(name = "MethodKey", targetNamespace = "http://tempuri.org/")
        java.lang.String methodKey,
        @WebParam(name = "AccountNo", targetNamespace = "http://tempuri.org/")
        java.lang.String accountNo,
        @WebParam(name = "SoftwareVendorCode", targetNamespace = "http://tempuri.org/")
        java.lang.Integer softwareVendorCode
    );

    @WebMethod(operationName = "AddMandate", action = "http://tempuri.org/INIWS_NIF/AddMandate")
    @Action(input = "http://tempuri.org/INIWS_NIF/AddMandate", output = "http://tempuri.org/INIWS_NIF/AddMandateResponse")
    @RequestWrapper(localName = "AddMandate", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.AddMandate")
    @ResponseWrapper(localName = "AddMandateResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.AddMandateResponse")
    @WebResult(name = "AddMandateResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.AddMandateResponse addMandate(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "AccountReference", targetNamespace = "http://tempuri.org/")
        java.lang.String accountReference,
        @WebParam(name = "MandateName", targetNamespace = "http://tempuri.org/")
        java.lang.String mandateName,
        @WebParam(name = "MandateAmount", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal mandateAmount,
        @WebParam(name = "IsConsumer", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean isConsumer,
        @WebParam(name = "FirstName", targetNamespace = "http://tempuri.org/")
        java.lang.String firstName,
        @WebParam(name = "Surname", targetNamespace = "http://tempuri.org/")
        java.lang.String surname,
        @WebParam(name = "TradingName", targetNamespace = "http://tempuri.org/")
        java.lang.String tradingName,
        @WebParam(name = "RegistrationNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String registrationNumber,
        @WebParam(name = "RegisteredName", targetNamespace = "http://tempuri.org/")
        java.lang.String registeredName,
        @WebParam(name = "MobileNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String mobileNumber,
        @WebParam(name = "DebitFrequency", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsMandateDebitFrequency debitFrequency,
        @WebParam(name = "CommencementMonth", targetNamespace = "http://tempuri.org/")
        java.lang.Integer commencementMonth,
        @WebParam(name = "CommencementDay", targetNamespace = "http://tempuri.org/")
        java.lang.String commencementDay,
        @WebParam(name = "AgreementDate", targetNamespace = "http://tempuri.org/")
        java.lang.String agreementDate,
        @WebParam(name = "AgreementReferenceNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String agreementReferenceNumber,
        @WebParam(name = "CancellationNoticePeriod", targetNamespace = "http://tempuri.org/")
        java.lang.Integer cancellationNoticePeriod,
        @WebParam(name = "PublicHolidayOption", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsMandatePublicHolidayOption publicHolidayOption,
        @WebParam(name = "Notes", targetNamespace = "http://tempuri.org/")
        java.lang.String notes,
        @WebParam(name = "Field1", targetNamespace = "http://tempuri.org/")
        java.lang.String field1,
        @WebParam(name = "Field2", targetNamespace = "http://tempuri.org/")
        java.lang.String field2,
        @WebParam(name = "Field3", targetNamespace = "http://tempuri.org/")
        java.lang.String field3,
        @WebParam(name = "Field4", targetNamespace = "http://tempuri.org/")
        java.lang.String field4,
        @WebParam(name = "Field5", targetNamespace = "http://tempuri.org/")
        java.lang.String field5,
        @WebParam(name = "Field6", targetNamespace = "http://tempuri.org/")
        java.lang.String field6,
        @WebParam(name = "Field7", targetNamespace = "http://tempuri.org/")
        java.lang.String field7,
        @WebParam(name = "Field8", targetNamespace = "http://tempuri.org/")
        java.lang.String field8,
        @WebParam(name = "Field9", targetNamespace = "http://tempuri.org/")
        java.lang.String field9,
        @WebParam(name = "AllowVariableDebitAmounts", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean allowVariableDebitAmounts,
        @WebParam(name = "BankDetailType", targetNamespace = "http://tempuri.org/")
        java.lang.Integer bankDetailType,
        @WebParam(name = "BankAccountName", targetNamespace = "http://tempuri.org/")
        java.lang.String bankAccountName,
        @WebParam(name = "BankAccountNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String bankAccountNumber,
        @WebParam(name = "BranchCode", targetNamespace = "http://tempuri.org/")
        java.lang.String branchCode,
        @WebParam(name = "BankAccountType", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsBankAccountType bankAccountType,
        @WebParam(name = "CreditCardToken", targetNamespace = "http://tempuri.org/")
        java.lang.String creditCardToken,
        @WebParam(name = "CreditCardType", targetNamespace = "http://tempuri.org/")
        java.lang.Integer creditCardType,
        @WebParam(name = "ExpiryMonth", targetNamespace = "http://tempuri.org/")
        java.lang.Integer expiryMonth,
        @WebParam(name = "ExpiryYear", targetNamespace = "http://tempuri.org/")
        java.lang.Integer expiryYear,
        @WebParam(name = "IsIdNumber", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean isIdNumber,
        @WebParam(name = "Title", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsTitle title,
        @WebParam(name = "EmailAddress", targetNamespace = "http://tempuri.org/")
        java.lang.String emailAddress,
        @WebParam(name = "PhoneNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String phoneNumber,
        @WebParam(name = "DateOfBirth", targetNamespace = "http://tempuri.org/")
        java.lang.String dateOfBirth,
        @WebParam(name = "DecemberDebitDay", targetNamespace = "http://tempuri.org/")
        java.lang.String decemberDebitDay,
        @WebParam(name = "DebitMasterfileGroup", targetNamespace = "http://tempuri.org/")
        java.lang.String debitMasterfileGroup,
        @WebParam(name = "PhysicalAddressLine1", targetNamespace = "http://tempuri.org/")
        java.lang.String physicalAddressLine1,
        @WebParam(name = "PhysicalAddressLine2", targetNamespace = "http://tempuri.org/")
        java.lang.String physicalAddressLine2,
        @WebParam(name = "PhysicalAddressLine3", targetNamespace = "http://tempuri.org/")
        java.lang.String physicalAddressLine3,
        @WebParam(name = "PhysicalSuburb", targetNamespace = "http://tempuri.org/")
        java.lang.String physicalSuburb,
        @WebParam(name = "PhysicalCity", targetNamespace = "http://tempuri.org/")
        java.lang.String physicalCity,
        @WebParam(name = "PhysicalProvince", targetNamespace = "http://tempuri.org/")
        java.lang.String physicalProvince,
        @WebParam(name = "PhysicalPostalCode", targetNamespace = "http://tempuri.org/")
        java.lang.String physicalPostalCode,
        @WebParam(name = "MandateActive", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean mandateActive,
        @WebParam(name = "RequestAVS", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean requestAVS,
        @WebParam(name = "AVSCheckNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String avsCheckNumber,
        @WebParam(name = "IncludeDebiCheck", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean includeDebiCheck,
        @WebParam(name = "DebiCheckMandateTemplateId", targetNamespace = "http://tempuri.org/")
        java.lang.String debiCheckMandateTemplateId,
        @WebParam(name = "DebiCheckCollectionAmount", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal debiCheckCollectionAmount,
        @WebParam(name = "DebiCheckFirstCollectionDiffers", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean debiCheckFirstCollectionDiffers,
        @WebParam(name = "DebiCheckFirstCollectionDate", targetNamespace = "http://tempuri.org/")
        java.lang.String debiCheckFirstCollectionDate,
        @WebParam(name = "DebiCheckFirstCollectionAmount", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal debiCheckFirstCollectionAmount,
        @WebParam(name = "DebiCheckCollectionDayCode", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckOptionsCollectionFrequencyDayCodes debiCheckCollectionDayCode,
        @WebParam(name = "AddToMasterFile", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean addToMasterFile
    );

    @WebMethod(operationName = "DebiCheckCancelAuthentication", action = "http://tempuri.org/INIWS_NIF/DebiCheckCancelAuthentication")
    @Action(input = "http://tempuri.org/INIWS_NIF/DebiCheckCancelAuthentication", output = "http://tempuri.org/INIWS_NIF/DebiCheckCancelAuthenticationResponse")
    @RequestWrapper(localName = "DebiCheckCancelAuthentication", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.DebiCheckCancelAuthentication")
    @ResponseWrapper(localName = "DebiCheckCancelAuthenticationResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.DebiCheckCancelAuthenticationResponse")
    @WebResult(name = "DebiCheckCancelAuthenticationResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String debiCheckCancelAuthentication(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "ContractReference", targetNamespace = "http://tempuri.org/")
        java.lang.String contractReference,
        @WebParam(name = "reasonCode", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckOptionsCancellationReasonCodes reasonCode
    );

    @WebMethod(operationName = "GetAvailableBalance", action = "http://tempuri.org/INIWS_NIF/GetAvailableBalance")
    @Action(input = "http://tempuri.org/INIWS_NIF/GetAvailableBalance", output = "http://tempuri.org/INIWS_NIF/GetAvailableBalanceResponse")
    @RequestWrapper(localName = "GetAvailableBalance", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.GetAvailableBalance")
    @ResponseWrapper(localName = "GetAvailableBalanceResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.GetAvailableBalanceResponse")
    @WebResult(name = "GetAvailableBalanceResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.GetAvailableBalanceResponse getAvailableBalance(

        @WebParam(name = "serviceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey
    );

    @WebMethod(operationName = "RetrieveBatchStatusByDate", action = "http://tempuri.org/INIWS_NIF/RetrieveBatchStatusByDate")
    @Action(input = "http://tempuri.org/INIWS_NIF/RetrieveBatchStatusByDate", output = "http://tempuri.org/INIWS_NIF/RetrieveBatchStatusByDateResponse")
    @RequestWrapper(localName = "RetrieveBatchStatusByDate", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveBatchStatusByDate")
    @ResponseWrapper(localName = "RetrieveBatchStatusByDateResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveBatchStatusByDateResponse")
    @WebResult(name = "RetrieveBatchStatusByDateResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String retrieveBatchStatusByDate(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
        java.lang.String endDate
    );

    @WebMethod(operationName = "RequestMerchantStatement", action = "http://tempuri.org/INIWS_NIF/RequestMerchantStatement")
    @Action(input = "http://tempuri.org/INIWS_NIF/RequestMerchantStatement", output = "http://tempuri.org/INIWS_NIF/RequestMerchantStatementResponse")
    @RequestWrapper(localName = "RequestMerchantStatement", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestMerchantStatement")
    @ResponseWrapper(localName = "RequestMerchantStatementResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestMerchantStatementResponse")
    @WebResult(name = "RequestMerchantStatementResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String requestMerchantStatement(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "FromActionDate", targetNamespace = "http://tempuri.org/")
        java.lang.String fromActionDate
    );

    @WebMethod(operationName = "RequestAVSReport", action = "http://tempuri.org/INIWS_NIF/RequestAVSReport")
    @Action(input = "http://tempuri.org/INIWS_NIF/RequestAVSReport", output = "http://tempuri.org/INIWS_NIF/RequestAVSReportResponse")
    @RequestWrapper(localName = "RequestAVSReport", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestAVSReport")
    @ResponseWrapper(localName = "RequestAVSReportResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestAVSReportResponse")
    @WebResult(name = "RequestAVSReportResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String requestAVSReport(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "FileToken", targetNamespace = "http://tempuri.org/")
        java.lang.String fileToken
    );

    @WebMethod(operationName = "RequestPayNowInvoice", action = "http://tempuri.org/INIWS_NIF/RequestPayNowInvoice")
    @Action(input = "http://tempuri.org/INIWS_NIF/RequestPayNowInvoice", output = "http://tempuri.org/INIWS_NIF/RequestPayNowInvoiceResponse")
    @RequestWrapper(localName = "RequestPayNowInvoice", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestPayNowInvoice")
    @ResponseWrapper(localName = "RequestPayNowInvoiceResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestPayNowInvoiceResponse")
    @WebResult(name = "RequestPayNowInvoiceResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String requestPayNowInvoice(

        @WebParam(name = "serviceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "fileToken", targetNamespace = "http://tempuri.org/")
        java.lang.String fileToken
    );

    @WebMethod(operationName = "GetPaymentLimits", action = "http://tempuri.org/INIWS_NIF/GetPaymentLimits")
    @Action(input = "http://tempuri.org/INIWS_NIF/GetPaymentLimits", output = "http://tempuri.org/INIWS_NIF/GetPaymentLimitsResponse")
    @RequestWrapper(localName = "GetPaymentLimits", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.GetPaymentLimits")
    @ResponseWrapper(localName = "GetPaymentLimitsResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.GetPaymentLimitsResponse")
    @WebResult(name = "GetPaymentLimitsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.LimitResponse getPaymentLimits(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey
    );

    @WebMethod(operationName = "DebiCheckRetrieveMandateTemplateDetail", action = "http://tempuri.org/INIWS_NIF/DebiCheckRetrieveMandateTemplateDetail")
    @Action(input = "http://tempuri.org/INIWS_NIF/DebiCheckRetrieveMandateTemplateDetail", output = "http://tempuri.org/INIWS_NIF/DebiCheckRetrieveMandateTemplateDetailResponse")
    @RequestWrapper(localName = "DebiCheckRetrieveMandateTemplateDetail", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.DebiCheckRetrieveMandateTemplateDetail")
    @ResponseWrapper(localName = "DebiCheckRetrieveMandateTemplateDetailResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.DebiCheckRetrieveMandateTemplateDetailResponse")
    @WebResult(name = "DebiCheckRetrieveMandateTemplateDetailResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckMandateTemplateDetail debiCheckRetrieveMandateTemplateDetail(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "DebiCheckMandateTemplateId", targetNamespace = "http://tempuri.org/")
        java.lang.String debiCheckMandateTemplateId
    );

    @WebMethod(operationName = "DebiCheckAuthenticate", action = "http://tempuri.org/INIWS_NIF/DebiCheckAuthenticate")
    @Action(input = "http://tempuri.org/INIWS_NIF/DebiCheckAuthenticate", output = "http://tempuri.org/INIWS_NIF/DebiCheckAuthenticateResponse")
    @RequestWrapper(localName = "DebiCheckAuthenticate", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.DebiCheckAuthenticate")
    @ResponseWrapper(localName = "DebiCheckAuthenticateResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.DebiCheckAuthenticateResponse")
    @WebResult(name = "DebiCheckAuthenticateResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckAuthenticateResponse debiCheckAuthenticate(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "AccountReference", targetNamespace = "http://tempuri.org/")
        java.lang.String accountReference,
        @WebParam(name = "DebiCheckMandateTemplateId", targetNamespace = "http://tempuri.org/")
        java.lang.String debiCheckMandateTemplateId,
        @WebParam(name = "IsIdNumber", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean isIdNumber,
        @WebParam(name = "DebtorIdentification", targetNamespace = "http://tempuri.org/")
        java.lang.String debtorIdentification,
        @WebParam(name = "AccountName", targetNamespace = "http://tempuri.org/")
        java.lang.String accountName,
        @WebParam(name = "BankAccountName", targetNamespace = "http://tempuri.org/")
        java.lang.String bankAccountName,
        @WebParam(name = "BranchCode", targetNamespace = "http://tempuri.org/")
        java.lang.String branchCode,
        @WebParam(name = "BankAccountNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String bankAccountNumber,
        @WebParam(name = "BankAccountType", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsBankAccountType bankAccountType,
        @WebParam(name = "MobileNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String mobileNumber,
        @WebParam(name = "EmailAddress", targetNamespace = "http://tempuri.org/")
        java.lang.String emailAddress,
        @WebParam(name = "CollectionAmount", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal collectionAmount,
        @WebParam(name = "FirstCollectionDiffers", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean firstCollectionDiffers,
        @WebParam(name = "FirstCollectionAmount", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal firstCollectionAmount,
        @WebParam(name = "FirstCollectionDate", targetNamespace = "http://tempuri.org/")
        java.lang.String firstCollectionDate,
        @WebParam(name = "collectionDayCode", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckOptionsCollectionFrequencyDayCodes collectionDayCode
    );

    @WebMethod(operationName = "RetrieveBlockedAccounts", action = "http://tempuri.org/INIWS_NIF/RetrieveBlockedAccounts")
    @Action(input = "http://tempuri.org/INIWS_NIF/RetrieveBlockedAccounts", output = "http://tempuri.org/INIWS_NIF/RetrieveBlockedAccountsResponse")
    @RequestWrapper(localName = "RetrieveBlockedAccounts", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveBlockedAccounts")
    @ResponseWrapper(localName = "RetrieveBlockedAccountsResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveBlockedAccountsResponse")
    @WebResult(name = "RetrieveBlockedAccountsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.RetrieveBlockedAccountsResponse retrieveBlockedAccounts(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
        java.lang.String endDate
    );

    @WebMethod(operationName = "RetrieveMultipleBatchStatus", action = "http://tempuri.org/INIWS_NIF/RetrieveMultipleBatchStatus")
    @Action(input = "http://tempuri.org/INIWS_NIF/RetrieveMultipleBatchStatus", output = "http://tempuri.org/INIWS_NIF/RetrieveMultipleBatchStatusResponse")
    @RequestWrapper(localName = "RetrieveMultipleBatchStatus", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveMultipleBatchStatus")
    @ResponseWrapper(localName = "RetrieveMultipleBatchStatusResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveMultipleBatchStatusResponse")
    @WebResult(name = "RetrieveMultipleBatchStatusResult", targetNamespace = "http://tempuri.org/")
    
    public java.lang.String retrieveMultipleBatchStatus(
        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "NumberOfBatches", targetNamespace = "http://tempuri.org/")
        java.lang.Integer numberOfBatches
    );

    @WebMethod(operationName = "DebiCheckAuthenticationCurrentStatus", action = "http://tempuri.org/INIWS_NIF/DebiCheckAuthenticationCurrentStatus")
    @Action(input = "http://tempuri.org/INIWS_NIF/DebiCheckAuthenticationCurrentStatus", output = "http://tempuri.org/INIWS_NIF/DebiCheckAuthenticationCurrentStatusResponse")
    @RequestWrapper(localName = "DebiCheckAuthenticationCurrentStatus", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.DebiCheckAuthenticationCurrentStatus")
    @ResponseWrapper(localName = "DebiCheckAuthenticationCurrentStatusResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.DebiCheckAuthenticationCurrentStatusResponse")
    @WebResult(name = "DebiCheckAuthenticationCurrentStatusResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckAuthenticationCurrentStatusResponse debiCheckAuthenticationCurrentStatus(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "ContractReference", targetNamespace = "http://tempuri.org/")
        java.lang.String contractReference
    );

    @WebMethod(operationName = "DebiCheckAmendAuthentication", action = "http://tempuri.org/INIWS_NIF/DebiCheckAmendAuthentication")
    @Action(input = "http://tempuri.org/INIWS_NIF/DebiCheckAmendAuthentication", output = "http://tempuri.org/INIWS_NIF/DebiCheckAmendAuthenticationResponse")
    @RequestWrapper(localName = "DebiCheckAmendAuthentication", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.DebiCheckAmendAuthentication")
    @ResponseWrapper(localName = "DebiCheckAmendAuthenticationResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.DebiCheckAmendAuthenticationResponse")
    @WebResult(name = "DebiCheckAmendAuthenticationResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckAmendmentResponse debiCheckAmendAuthentication(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "ContractReference", targetNamespace = "http://tempuri.org/")
        java.lang.String contractReference,
        @WebParam(name = "CollectionAmountInCents", targetNamespace = "http://tempuri.org/")
        java.lang.Long collectionAmountInCents,
        @WebParam(name = "MaximumCollectionAmountInCents", targetNamespace = "http://tempuri.org/")
        java.lang.Long maximumCollectionAmountInCents
    );

    @WebMethod(operationName = "RequestCombinedUploadReportForDate", action = "http://tempuri.org/INIWS_NIF/RequestCombinedUploadReportForDate")
    @Action(input = "http://tempuri.org/INIWS_NIF/RequestCombinedUploadReportForDate", output = "http://tempuri.org/INIWS_NIF/RequestCombinedUploadReportForDateResponse")
    @RequestWrapper(localName = "RequestCombinedUploadReportForDate", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestCombinedUploadReportForDate")
    @ResponseWrapper(localName = "RequestCombinedUploadReportForDateResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestCombinedUploadReportForDateResponse")
    @WebResult(name = "RequestCombinedUploadReportForDateResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String requestCombinedUploadReportForDate(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "Date", targetNamespace = "http://tempuri.org/")
        java.lang.String date
    );

    @WebMethod(operationName = "GetDebitLimits", action = "http://tempuri.org/INIWS_NIF/GetDebitLimits")
    @Action(input = "http://tempuri.org/INIWS_NIF/GetDebitLimits", output = "http://tempuri.org/INIWS_NIF/GetDebitLimitsResponse")
    @RequestWrapper(localName = "GetDebitLimits", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.GetDebitLimits")
    @ResponseWrapper(localName = "GetDebitLimitsResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.GetDebitLimitsResponse")
    @WebResult(name = "GetDebitLimitsResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.LimitResponse getDebitLimits(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey
    );

    @WebMethod(operationName = "RequestCreditDataReport", action = "http://tempuri.org/INIWS_NIF/RequestCreditDataReport")
    @Action(input = "http://tempuri.org/INIWS_NIF/RequestCreditDataReport", output = "http://tempuri.org/INIWS_NIF/RequestCreditDataReportResponse")
    @RequestWrapper(localName = "RequestCreditDataReport", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestCreditDataReport")
    @ResponseWrapper(localName = "RequestCreditDataReportResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestCreditDataReportResponse")
    @WebResult(name = "RequestCreditDataReportResult", targetNamespace = "http://tempuri.org/")
    public com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring requestCreditDataReport(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "FileToken", targetNamespace = "http://tempuri.org/")
        java.lang.String fileToken
    );

    @WebMethod(operationName = "RequestBatchAuthorise", action = "http://tempuri.org/INIWS_NIF/RequestBatchAuthorise")
    @Action(input = "http://tempuri.org/INIWS_NIF/RequestBatchAuthorise", output = "http://tempuri.org/INIWS_NIF/RequestBatchAuthoriseResponse")
    @RequestWrapper(localName = "RequestBatchAuthorise", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestBatchAuthorise")
    @ResponseWrapper(localName = "RequestBatchAuthoriseResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestBatchAuthoriseResponse")
    @WebResult(name = "RequestBatchAuthoriseResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String requestBatchAuthorise(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "BatchIndicator", targetNamespace = "http://tempuri.org/")
        java.lang.String batchIndicator,
        @WebParam(name = "SendEmail", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean sendEmail,
        @WebParam(name = "FromName", targetNamespace = "http://tempuri.org/")
        java.lang.String fromName,
        @WebParam(name = "FromAddress", targetNamespace = "http://tempuri.org/")
        java.lang.String fromAddress,
        @WebParam(name = "SendSMS", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean sendSMS,
        @WebParam(name = "ReleaseFunds", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean releaseFunds,
        @WebParam(name = "BankTransfer", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean bankTransfer
    );

    @WebMethod(operationName = "RequestDebitBatchUnauthorised", action = "http://tempuri.org/INIWS_NIF/RequestDebitBatchUnauthorised")
    @Action(input = "http://tempuri.org/INIWS_NIF/RequestDebitBatchUnauthorised", output = "http://tempuri.org/INIWS_NIF/RequestDebitBatchUnauthorisedResponse")
    @RequestWrapper(localName = "RequestDebitBatchUnauthorised", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestDebitBatchUnauthorised")
    @ResponseWrapper(localName = "RequestDebitBatchUnauthorisedResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestDebitBatchUnauthorisedResponse")
    @WebResult(name = "RequestDebitBatchUnauthorisedResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String requestDebitBatchUnauthorised(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "Date", targetNamespace = "http://tempuri.org/")
        java.lang.String date
    );

    @WebMethod(operationName = "RetrieveBatchStatus", action = "http://tempuri.org/INIWS_NIF/RetrieveBatchStatus")
    @Action(input = "http://tempuri.org/INIWS_NIF/RetrieveBatchStatus", output = "http://tempuri.org/INIWS_NIF/RetrieveBatchStatusResponse")
    @RequestWrapper(localName = "RetrieveBatchStatus", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveBatchStatus")
    @ResponseWrapper(localName = "RetrieveBatchStatusResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveBatchStatusResponse")
    @WebResult(name = "RetrieveBatchStatusResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String retrieveBatchStatus(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey
    );

    @WebMethod(operationName = "RetrieveMandateData", action = "http://tempuri.org/INIWS_NIF/RetrieveMandateData")
    @Action(input = "http://tempuri.org/INIWS_NIF/RetrieveMandateData", output = "http://tempuri.org/INIWS_NIF/RetrieveMandateDataResponse")
    @RequestWrapper(localName = "RetrieveMandateData", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveMandateData")
    @ResponseWrapper(localName = "RetrieveMandateDataResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveMandateDataResponse")
    @WebResult(name = "RetrieveMandateDataResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String retrieveMandateData(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "FileToken", targetNamespace = "http://tempuri.org/")
        java.lang.String fileToken
    );

    @WebMethod(operationName = "RequestMandateData", action = "http://tempuri.org/INIWS_NIF/RequestMandateData")
    @Action(input = "http://tempuri.org/INIWS_NIF/RequestMandateData", output = "http://tempuri.org/INIWS_NIF/RequestMandateDataResponse")
    @RequestWrapper(localName = "RequestMandateData", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestMandateData")
    @ResponseWrapper(localName = "RequestMandateDataResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestMandateDataResponse")
    @WebResult(name = "RequestMandateDataResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String requestMandateData(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey
    );

    @WebMethod(operationName = "LegacyCompactBatchFileUpload", action = "http://tempuri.org/INIWS_NIF/LegacyCompactBatchFileUpload")
    @Action(input = "http://tempuri.org/INIWS_NIF/LegacyCompactBatchFileUpload", output = "http://tempuri.org/INIWS_NIF/LegacyCompactBatchFileUploadResponse")
    @RequestWrapper(localName = "LegacyCompactBatchFileUpload", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.LegacyCompactBatchFileUpload")
    @ResponseWrapper(localName = "LegacyCompactBatchFileUploadResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.LegacyCompactBatchFileUploadResponse")
    @WebResult(name = "LegacyCompactBatchFileUploadResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String legacyCompactBatchFileUpload(

        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "PIN", targetNamespace = "http://tempuri.org/")
        java.lang.String pin,
        @WebParam(name = "File", targetNamespace = "http://tempuri.org/")
        java.lang.String file,
        @WebParam(name = "ProcessAsLegacy", targetNamespace = "http://tempuri.org/")
        java.lang.String processAsLegacy
    );

    @WebMethod(operationName = "LegacyBatchFileUpload", action = "http://tempuri.org/INIWS_NIF/LegacyBatchFileUpload")
    @Action(input = "http://tempuri.org/INIWS_NIF/LegacyBatchFileUpload", output = "http://tempuri.org/INIWS_NIF/LegacyBatchFileUploadResponse")
    @RequestWrapper(localName = "LegacyBatchFileUpload", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.LegacyBatchFileUpload")
    @ResponseWrapper(localName = "LegacyBatchFileUploadResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.LegacyBatchFileUploadResponse")
    @WebResult(name = "LegacyBatchFileUploadResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String legacyBatchFileUpload(

        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "PIN", targetNamespace = "http://tempuri.org/")
        java.lang.String pin,
        @WebParam(name = "File", targetNamespace = "http://tempuri.org/")
        java.lang.String file,
        @WebParam(name = "ProcessAsLegacy", targetNamespace = "http://tempuri.org/")
        java.lang.String processAsLegacy
    );

    @WebMethod(operationName = "AVSRealtimeQuery", action = "http://tempuri.org/INIWS_NIF/AVSRealtimeQuery")
    @Action(input = "http://tempuri.org/INIWS_NIF/AVSRealtimeQuery", output = "http://tempuri.org/INIWS_NIF/AVSRealtimeQueryResponse")
    @RequestWrapper(localName = "AVSRealtimeQuery", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.AVSRealtimeQuery")
    @ResponseWrapper(localName = "AVSRealtimeQueryResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.AVSRealtimeQueryResponse")
    @WebResult(name = "AVSRealtimeQueryResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.AVSRealtimeQueryResponse avsRealtimeQuery(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "AccountReference", targetNamespace = "http://tempuri.org/")
        java.lang.String accountReference,
        @WebParam(name = "Extra1", targetNamespace = "http://tempuri.org/")
        java.lang.String extra1,
        @WebParam(name = "Extra2", targetNamespace = "http://tempuri.org/")
        java.lang.String extra2,
        @WebParam(name = "Extra3", targetNamespace = "http://tempuri.org/")
        java.lang.String extra3,
        @WebParam(name = "BankAccountNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String bankAccountNumber,
        @WebParam(name = "BranchCode", targetNamespace = "http://tempuri.org/")
        java.lang.String branchCode,
        @WebParam(name = "BankAccountType", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsBankAccountType bankAccountType,
        @WebParam(name = "EnquiryName", targetNamespace = "http://tempuri.org/")
        java.lang.String enquiryName,
        @WebParam(name = "Initials", targetNamespace = "http://tempuri.org/")
        java.lang.String initials,
        @WebParam(name = "IdNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String idNumber,
        @WebParam(name = "IsIdNumber", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean isIdNumber,
        @WebParam(name = "PhoneNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String phoneNumber,
        @WebParam(name = "Email", targetNamespace = "http://tempuri.org/")
        java.lang.String email
    );

    @WebMethod(operationName = "RetrieveMerchantStatement", action = "http://tempuri.org/INIWS_NIF/RetrieveMerchantStatement")
    @Action(input = "http://tempuri.org/INIWS_NIF/RetrieveMerchantStatement", output = "http://tempuri.org/INIWS_NIF/RetrieveMerchantStatementResponse")
    @RequestWrapper(localName = "RetrieveMerchantStatement", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveMerchantStatement")
    @ResponseWrapper(localName = "RetrieveMerchantStatementResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveMerchantStatementResponse")
    @WebResult(name = "RetrieveMerchantStatementResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String retrieveMerchantStatement(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "PollingId", targetNamespace = "http://tempuri.org/")
        java.lang.String pollingId
    );

    @WebMethod(operationName = "RequestFileUploadReport", action = "http://tempuri.org/INIWS_NIF/RequestFileUploadReport")
    @Action(input = "http://tempuri.org/INIWS_NIF/RequestFileUploadReport", output = "http://tempuri.org/INIWS_NIF/RequestFileUploadReportResponse")
    @RequestWrapper(localName = "RequestFileUploadReport", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestFileUploadReport")
    @ResponseWrapper(localName = "RequestFileUploadReportResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestFileUploadReportResponse")
    @WebResult(name = "RequestFileUploadReportResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String requestFileUploadReport(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "FileToken", targetNamespace = "http://tempuri.org/")
        java.lang.String fileToken
    );

    @WebMethod(operationName = "RetrieveMandatePDF", action = "http://tempuri.org/INIWS_NIF/RetrieveMandatePDF")
    @Action(input = "http://tempuri.org/INIWS_NIF/RetrieveMandatePDF", output = "http://tempuri.org/INIWS_NIF/RetrieveMandatePDFResponse")
    @RequestWrapper(localName = "RetrieveMandatePDF", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveMandatePDF")
    @ResponseWrapper(localName = "RetrieveMandatePDFResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RetrieveMandatePDFResponse")
    @WebResult(name = "RetrieveMandatePDFResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String retrieveMandatePDF(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "FileToken", targetNamespace = "http://tempuri.org/")
        java.lang.String fileToken
    );

    @WebMethod(operationName = "AccountFundsTransfer", action = "http://tempuri.org/INIWS_NIF/AccountFundsTransfer")
    @Action(input = "http://tempuri.org/INIWS_NIF/AccountFundsTransfer", output = "http://tempuri.org/INIWS_NIF/AccountFundsTransferResponse")
    @RequestWrapper(localName = "AccountFundsTransfer", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.AccountFundsTransfer")
    @ResponseWrapper(localName = "AccountFundsTransferResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.AccountFundsTransferResponse")
    @WebResult(name = "AccountFundsTransferResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.AccountFundsTransferResponse accountFundsTransfer(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "ToAccountNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String toAccountNumber,
        @WebParam(name = "BeneficiaryReference", targetNamespace = "http://tempuri.org/")
        java.lang.String beneficiaryReference,
        @WebParam(name = "AmountInCents", targetNamespace = "http://tempuri.org/")
        java.lang.Long amountInCents
    );

    @WebMethod(operationName = "RequestActionDate", action = "http://tempuri.org/INIWS_NIF/RequestActionDate")
    @Action(input = "http://tempuri.org/INIWS_NIF/RequestActionDate", output = "http://tempuri.org/INIWS_NIF/RequestActionDateResponse")
    @RequestWrapper(localName = "RequestActionDate", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestActionDate")
    @ResponseWrapper(localName = "RequestActionDateResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestActionDateResponse")
    @WebResult(name = "RequestActionDateResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String requestActionDate(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "Date", targetNamespace = "http://tempuri.org/")
        java.lang.String date,
        @WebParam(name = "Instruction", targetNamespace = "http://tempuri.org/")
        java.lang.String instruction,
        @WebParam(name = "ForwardActionDate", targetNamespace = "http://tempuri.org/")
        java.lang.String forwardActionDate
    );

    @WebMethod(operationName = "RequestInterimMerchantStatement", action = "http://tempuri.org/INIWS_NIF/RequestInterimMerchantStatement")
    @Action(input = "http://tempuri.org/INIWS_NIF/RequestInterimMerchantStatement", output = "http://tempuri.org/INIWS_NIF/RequestInterimMerchantStatementResponse")
    @RequestWrapper(localName = "RequestInterimMerchantStatement", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestInterimMerchantStatement")
    @ResponseWrapper(localName = "RequestInterimMerchantStatementResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.RequestInterimMerchantStatementResponse")
    @WebResult(name = "RequestInterimMerchantStatementResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String requestInterimMerchantStatement(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey
    );

    @WebMethod(operationName = "MerchantStatementSourceStatus", action = "http://tempuri.org/INIWS_NIF/MerchantStatementSourceStatus")
    @Action(input = "http://tempuri.org/INIWS_NIF/MerchantStatementSourceStatus", output = "http://tempuri.org/INIWS_NIF/MerchantStatementSourceStatusResponse")
    @RequestWrapper(localName = "MerchantStatementSourceStatus", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.MerchantStatementSourceStatus")
    @ResponseWrapper(localName = "MerchantStatementSourceStatusResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.MerchantStatementSourceStatusResponse")
    @WebResult(name = "MerchantStatementSourceStatusResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MerchantStatementSourceStatusResponse merchantStatementSourceStatus(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "Date", targetNamespace = "http://tempuri.org/")
        java.lang.String date
    );

    @WebMethod(operationName = "IsValidServiceKey", action = "http://tempuri.org/INIWS_NIF/IsValidServiceKey")
    @Action(input = "http://tempuri.org/INIWS_NIF/IsValidServiceKey", output = "http://tempuri.org/INIWS_NIF/IsValidServiceKeyResponse")
    @RequestWrapper(localName = "IsValidServiceKey", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.IsValidServiceKey")
    @ResponseWrapper(localName = "IsValidServiceKeyResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.IsValidServiceKeyResponse")
    @WebResult(name = "IsValidServiceKeyResult", targetNamespace = "http://tempuri.org/")
    public com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring isValidServiceKey(

        @WebParam(name = "MethodKey", targetNamespace = "http://tempuri.org/")
        java.lang.String methodKey,
        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "InstructionCode", targetNamespace = "http://tempuri.org/")
        java.lang.String instructionCode,
        @WebParam(name = "SofwareVendorCode", targetNamespace = "http://tempuri.org/")
        java.lang.Integer sofwareVendorCode
    );

    @WebMethod(operationName = "BatchFileUpload", action = "http://tempuri.org/INIWS_NIF/BatchFileUpload")
    @Action(input = "http://tempuri.org/INIWS_NIF/BatchFileUpload", output = "http://tempuri.org/INIWS_NIF/BatchFileUploadResponse")
    @RequestWrapper(localName = "BatchFileUpload", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.BatchFileUpload")
    @ResponseWrapper(localName = "BatchFileUploadResponse", targetNamespace = "http://tempuri.org/", className = "za.co.WebServices.BatchFileUploadResponse")
    @WebResult(name = "BatchFileUploadResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String batchFileUpload(

        @WebParam(name = "ServiceKey", targetNamespace = "http://tempuri.org/")
        java.lang.String serviceKey,
        @WebParam(name = "File", targetNamespace = "http://tempuri.org/")
        java.lang.String file
    );
}
