package za.co.WebServices;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.1.3
 * 2025-08-26T12:12:00.407+02:00
 * Generated source version: 4.1.3
 *
 */
@WebServiceClient(name = "NIWS_NIF",
                  wsdlLocation = "https://ws.netcash.co.za/NIWS/NIWS_NIF.svc?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class NIWSNIF extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://tempuri.org/", "NIWS_NIF");
    public static final QName BasicHttpBindingINIWSNIF = new QName("http://tempuri.org/", "BasicHttpBinding_INIWS_NIF");
    static {
        URL url = null;
        try {
            url = URI.create("https://ws.netcash.co.za/NIWS/NIWS_NIF.svc?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NIWSNIF.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://ws.netcash.co.za/NIWS/NIWS_NIF.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NIWSNIF(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NIWSNIF(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NIWSNIF() {
        super(WSDL_LOCATION, SERVICE);
    }

    public NIWSNIF(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public NIWSNIF(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public NIWSNIF(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns INIWSNIF
     */
    @WebEndpoint(name = "BasicHttpBinding_INIWS_NIF")
    public INIWSNIF getBasicHttpBindingINIWSNIF() {
        return super.getPort(BasicHttpBindingINIWSNIF, INIWSNIF.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns INIWSNIF
     */
    @WebEndpoint(name = "BasicHttpBinding_INIWS_NIF")
    public INIWSNIF getBasicHttpBindingINIWSNIF(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingINIWSNIF, INIWSNIF.class, features);
    }

}
