
package za.co.WebServices.clients;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;
import za.co.WebServices.INIWSNIF;
import za.co.WebServices.NIWSNIF;

/**
 * This class was generated by Apache CXF 4.1.3
 * 2025-08-26T12:12:00.163+02:00
 * Generated source version: 4.1.3
 *
 */
public final class INIWSNIF_BasicHttpBindingINIWSNIF_Client {
    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "NIWS_NIF");
    private static final String DEBIT_ORDER_SERVICE_KEY = "d0a5c3ef-98ef-4f9a-b8d7-c6503721a8ff";
    private static final String ACCOUNT_SERVICE_KEY = "57265240-331e-41cd-b079-d99f31ccef69";
    
    private static final int RETRIEVE_WAIT_TIME = 2000;
    
    private static ArrayList soapDateArrayList=new ArrayList();
    static INIWSNIF port ;

    public INIWSNIF_BasicHttpBindingINIWSNIF_Client() {
    	basicHttpBindingINIWSNIF();	
    }
    
    public void basicHttpBindingINIWSNIF() {
   	 URL wsdlURL = NIWSNIF.WSDL_LOCATION;	      
		 NIWSNIF ss = new NIWSNIF(wsdlURL, SERVICE_NAME);
		 port = ss.getBasicHttpBindingINIWSNIF();   	
   }

    public static void main(String args[]) throws Exception {
         {
        	soapDateArrayList.clear();
            System.out.println("Invoking retrieveMultipleBatchStatus...");
            String _retrieveMultipleBatchStatus_serviceKey = DEBIT_ORDER_SERVICE_KEY;
            Integer _retrieveMultipleBatchStatus_numberOfBatches = Integer.valueOf(1);
            String _retrieveMultipleBatchStatus__return = port.retrieveMultipleBatchStatus(_retrieveMultipleBatchStatus_serviceKey, _retrieveMultipleBatchStatus_numberOfBatches);
            //System.out.println("retrieveMultipleBatchStatus.result=\n" + _retrieveMultipleBatchStatus__return);
            
            //String statusResponse = netcashClient.retrieveMultipleBatchStatus(serviceKey);
            // Split into lines
            String[] batches = _retrieveMultipleBatchStatus__return.split("\n");
            int i=-1;
            for (String batchLine : batches){
            	i+=1;
            	//System.out.println("batchLine:["+i+"] " + batchLine);                
            	// Split each line by tab
            	String[] fields = batchLine.split("\t");
            	System.out.println("FIELD_LENGTH: "+fields.length);
            	String serviceKey=fields[0];
            	String batchId=fields[1];
            	String batchName=fields[2];
            	String debitDate=batchName.replace("Debit batch for", "").trim();
            	System.out.println("DebitDate: " + debitDate+ " --->"+getSoapDate(debitDate, "dd MMM yyyy")); 
            	LocalDate today = LocalDate.now();
            	System.out.println("TodayDate: " + today); 
            	if(!getSoapDate(today.toString(), "yyyy-MM-dd").equals(getSoapDate(debitDate, "dd MMM yyyy"))) {
            		soapDateArrayList.add(getSoapDate(debitDate, "dd MMM yyyy"));
            	}
            	String batchStatus=fields[3];
            	String batchVolume=fields[4];
            	String batchValue=fields[5];
            	String createdDate=fields[6];
            	String authorisedDate=fields[7];
            	String unauthorisedDate=fields[8];
            	//fields[0] = Batch ID, fields[1] = Status Code, fields[2] = Status Description
            	System.out.println("Service Key: " + serviceKey + ", Batch ID: " + batchId + ", Batch Name: " + batchName+ ", Status: " + batchStatus+ ", Batch Volume: " + batchVolume+ ", Batch Value: " + batchValue+ ", Created on: " + createdDate+ ", Authorised on: " + authorisedDate+ ", Unauthorised on: " + unauthorisedDate);
            	
            	String debitOrderBatchColumn="batch_id, batch_name, debit_date, batch_status, batch_volume, created_date, authorised_date, unauthorised_date";
            	String debitOrderBatchValue=" "+batchId+", '"+batchName+"', TO_DATE('"+debitDate+"','DD MON YYYY'), "+batchStatus+" , "+batchVolume+", TO_DATE('"+createdDate+"', 'YYYY-MM-DD HH:MI:SS.MS'), TO_DATE('"+authorisedDate+"', 'YYYY-MM-DD HH:MI:SS.MS'), TO_DATE('"+unauthorisedDate+"', 'YYYY-MM-DD HH:MI:SS.MS') ";
            	String INSERT_DEBIT_BATCH_SQL="INSERT INTO debit_order_batch ("+debitOrderBatchColumn+") VALUES("+debitOrderBatchValue+")";
            	System.out.println("INSERT_DEBIT_BATCH_SQL: "+INSERT_DEBIT_BATCH_SQL);
            }           
        }
        {
        for(int i=0;i<soapDateArrayList.size(); i++){
            System.out.println("Invoking requestMerchantStatement...");
            String _requestMerchantStatement_serviceKey = ACCOUNT_SERVICE_KEY;
            String _requestMerchantStatement_fromActionDate = soapDateArrayList.get(i).toString();
            System.out.println("SOAP_DATE: "+_requestMerchantStatement_fromActionDate);
            String _requestMerchantStatement__pollingId = port.requestMerchantStatement(_requestMerchantStatement_serviceKey, _requestMerchantStatement_fromActionDate);
            System.out.println("requestMerchantStatement.result=\n" + _requestMerchantStatement__pollingId);
            //----------------------------------------------------------------------------------------------------
            //SLEEPING will avoid having "FILE NOT READY" error by retreiving before file is COMPLETE
            Thread.sleep(RETRIEVE_WAIT_TIME);
            System.err.println("Invoking retrieveMerchantStatement in: "+ RETRIEVE_WAIT_TIME/1000+ " Seconds\n");          
            
            String _retrieveMerchantStatement_serviceKey = ACCOUNT_SERVICE_KEY;
            String _retrieveMerchantStatement_pollingId = _requestMerchantStatement__pollingId;
            String _retrieveMerchantStatement__return = port.retrieveMerchantStatement(_retrieveMerchantStatement_serviceKey, _retrieveMerchantStatement_pollingId);
            System.out.println("retrieveMerchantStatement.result=\n" + _retrieveMerchantStatement__return);
            
            if(_retrieveMerchantStatement__return.equals("FILE NOT READY")) {
            	Thread.sleep(RETRIEVE_WAIT_TIME);   
            	System.err.println(_requestMerchantStatement__pollingId+" For: "+ _requestMerchantStatement_fromActionDate+": FILE NOT READY trying again in: "+ RETRIEVE_WAIT_TIME/1000+ " Seconds\n");
            	_retrieveMerchantStatement__return = port.retrieveMerchantStatement(_retrieveMerchantStatement_serviceKey, _retrieveMerchantStatement_pollingId);
                
            }
            
            //Split into lines
            String[] merchantStatement = _retrieveMerchantStatement__return.split("\n");
            int j=-1;
            for (String merchantStatementLine : merchantStatement){
            	j+=1;
            	System.out.println("merchantStatementLine:["+j+"] " + merchantStatementLine);                
            	// Split each line by tab
            	String[] statementfields = merchantStatementLine.split("\t");
            	System.out.println("FIELD_LENGTH: "+statementfields.length);
            	String transactionDate=statementfields[0];
            	String transactionType=statementfields[1];
            	String transactionId=statementfields[2];
            	String transactionDescription=statementfields[3];
            	String transactionAmount=statementfields[4];
            	String symbol=statementfields[5];
            	//System.out.println("Symbo Description: "+getSymbolDescription(symbol));            	
            	String vat=statementfields[6];            	
            	System.out.println("Transaction_Date: " + transactionDate + ", Transaction_Type: " + transactionType + ", transaction_Id: " + transactionId+ ", Transaction_Description: " + transactionDescription+ ", Transaction_Amount: " + transactionAmount+ ", Symbol: " +getSymbolDescription(symbol)+ ", VAT: " + vat);
            }
        }
            
         }
        {
            System.out.println("Invoking requestMandateData...");
            String _requestMandateData_serviceKey = DEBIT_ORDER_SERVICE_KEY;
            String _requestMandateData__return = port.requestMandateData(_requestMandateData_serviceKey);
            System.out.println("requestMandateData.result=" + _requestMandateData__return);

            //SLEEPING will avoid having "FILE NOT READY" error by retreiving before file is COMPLETE
            Thread.sleep(5*RETRIEVE_WAIT_TIME);
            System.out.println("Invoking retrieveMandateData...");
            String _retrieveMandateData_serviceKey = DEBIT_ORDER_SERVICE_KEY;
            String _retrieveMandateData_fileToken = _requestMandateData__return/*"_retrieveMandateData_fileToken-1149111475"*/;
            String _retrieveMandateData__return = port.retrieveMandateData(_retrieveMandateData_serviceKey, _retrieveMandateData_fileToken);
            System.out.println("retrieveMandateData.result=" + _retrieveMandateData__return);
        
            if(_retrieveMandateData__return.equals("FILE NOT READY")) {
            	System.out.println("Invoking retrieveMandateData AGAIN... ");
            	Thread.sleep(10*RETRIEVE_WAIT_TIME);   
            	System.err.println(_requestMandateData__return+" For: "+ "_requestMerchantStatement_fromActionDate"+": FILE NOT READY trying again in: "+ RETRIEVE_WAIT_TIME/1000+ " Seconds\n");
            	_retrieveMandateData__return = port.retrieveMandateData(_retrieveMandateData_serviceKey, _retrieveMandateData_fileToken);
            	System.out.println("retrieveMandateData.result=" + _retrieveMandateData__return);
                          
            }
            
            //Split into lines
            String[] mandateData = _retrieveMandateData__return.split("\n");
            int j=-1;
            for (String mandateDataLine : mandateData){
            	j+=1;
            	System.out.println("mandateDataLine:["+j+"] " + mandateDataLine);   
            	if(!(mandateDataLine.contains("BEGIN")||mandateDataLine.contains("###END"))) {
            		// Split each line by tab
            		String[] mandateDatafields = mandateDataLine.split("\t");
            		System.out.println("FIELD_LENGTH: "+mandateDatafields.length);
            		String _addMandate_serviceKey = mandateDatafields[0];
            		String accountReference = mandateDatafields[1];
            		System.out.println("accountReference: "+ accountReference);
            		String mandateName = mandateDatafields[2];
            		System.out.println("mandateName: "+ mandateName);
            		java.math.BigDecimal mandateAmount = new java.math.BigDecimal(mandateDatafields[3]);
            		System.out.println("mandateAmount: "+ mandateAmount);
            		String isActive = mandateDatafields[4];
            		System.out.println("isActive: "+ isActive);
            		String firstName = mandateDatafields[5];
            		System.out.println("firstName: "+ firstName);
            		String surname = mandateDatafields[6];
            		System.out.println("surname: "+ surname);
            		Integer commencementMonth = Integer.valueOf(mandateDatafields[12]);
            		System.out.println("commencementMonth: "+ commencementMonth);
            		String commencementDay = mandateDatafields[13];
            		System.out.println("commencementDay: "+ commencementDay);
            		
                /*String _addMandate_tradingName = mandateDatafields[7];
                String _addMandate_registrationNumber = mandateDatafields[8];
                String _addMandate_registeredName = mandateDatafields[9];
                String _addMandate_mobileNumber = mandateDatafields[10];
               // org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsMandateDebitFrequency _addMandate_debitFrequency = org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsMandateDebitFrequency.ANNUALLY;
                Integer _addMandate_commencementMonth = Integer.valueOf(mandateDatafields[12]);
                String _addMandate_commencementDay = mandateDatafields[13];
                String _addMandate_agreementDate = mandateDatafields[14];
                String _addMandate_agreementReferenceNumber = mandateDatafields[15];
                Integer _addMandate_cancellationNoticePeriod = Integer.valueOf(mandateDatafields[16]);
                //org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsMandatePublicHolidayOption _addMandate_publicHolidayOption = org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsMandatePublicHolidayOption.VERY_NEXT_ORDINARY_BUSINESS_DAY;
                String _addMandate_notes = mandateDatafields[18];
                String _addMandate_field1 = "_addMandate_field1537755104";
                String _addMandate_field2 = "_addMandate_field2-2145934059";
                String _addMandate_field3 = "_addMandate_field3-1203647155";
                String _addMandate_field4 = "_addMandate_field4770037184";
                String _addMandate_field5 = "_addMandate_field5-1656596936";
                String _addMandate_field6 = "_addMandate_field6-80940020";
                String _addMandate_field7 = "_addMandate_field71132875069";
                String _addMandate_field8 = "_addMandate_field82127505320";
                String _addMandate_field9 = "_addMandate_field9-743632357";
                Boolean _addMandate_allowVariableDebitAmounts = Boolean.valueOf(true);
                Integer _addMandate_bankDetailType = Integer.valueOf(-377057399);
                String _addMandate_bankAccountName = mandateDatafields[0];
                String _addMandate_bankAccountNumber = mandateDatafields[0];
                String _addMandate_branchCode = mandateDatafields[0];
               // org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsBankAccountType _addMandate_bankAccountType = org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsBankAccountType.SAVINGS;
                String _addMandate_creditCardToken = "_addMandate_creditCardToken2004005626";
                Integer _addMandate_creditCardType = Integer.valueOf(-421386615);
                Integer _addMandate_expiryMonth = Integer.valueOf(300291947);
                Integer _addMandate_expiryYear = Integer.valueOf(-1951612343);
                Boolean _addMandate_isIdNumber = Boolean.valueOf(false);
                org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsTitle _addMandate_title = org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsTitle.NOT_SET;
                String _addMandate_emailAddress = "_addMandate_emailAddress-1700681861";
                String _addMandate_phoneNumber = "_addMandate_phoneNumber-142545521";
                String _addMandate_dateOfBirth = "_addMandate_dateOfBirth-1792471886";
                String _addMandate_decemberDebitDay = "_addMandate_decemberDebitDay-1632779555";
                String _addMandate_debitMasterfileGroup = "_addMandate_debitMasterfileGroup-1019891781";
                String _addMandate_physicalAddressLine1 = "_addMandate_physicalAddressLine1642355835";
                String _addMandate_physicalAddressLine2 = "_addMandate_physicalAddressLine2-1713035694";
                String _addMandate_physicalAddressLine3 = "_addMandate_physicalAddressLine31576409507";
                String _addMandate_physicalSuburb = "_addMandate_physicalSuburb-877327803";
                String _addMandate_physicalCity = "_addMandate_physicalCity-496925659";
                String _addMandate_physicalProvince = "_addMandate_physicalProvince-1479081680";
                String _addMandate_physicalPostalCode = "_addMandate_physicalPostalCode827364768";
                Boolean _addMandate_mandateActive = Boolean.valueOf(true);
                Boolean _addMandate_requestAVS = Boolean.valueOf(false);
                String _addMandate_avsCheckNumber = "_addMandate_avsCheckNumber-1188264657";
                Boolean _addMandate_includeDebiCheck = Boolean.valueOf(true);
                String _addMandate_debiCheckMandateTemplateId = "_addMandate_debiCheckMandateTemplateId-925776377";
                java.math.BigDecimal _addMandate_debiCheckCollectionAmount = new java.math.BigDecimal("7532901501064870651.4576073574570406561");
                Boolean _addMandate_debiCheckFirstCollectionDiffers = Boolean.valueOf(true);
                String _addMandate_debiCheckFirstCollectionDate = "_addMandate_debiCheckFirstCollectionDate127444593";
                java.math.BigDecimal _addMandate_debiCheckFirstCollectionAmount = new java.math.BigDecimal("1558179552122738196.7368972155657823038");
                org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckOptionsCollectionFrequencyDayCodes _addMandate_debiCheckCollectionDayCode = org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckOptionsCollectionFrequencyDayCodes.ADHO_10;
                Boolean _addMandate_addToMasterFile = Boolean.valueOf(true);*/

            	//System.out.println("Transaction_Date: " + transactionDate + ", Transaction_Type: " + transactionType + ", transaction_Id: " + transactionId+ ", Transaction_Description: " + transactionDescription+ ", Transaction_Amount: " + transactionAmount+ ", Symbol: " +getSymbolDescription(symbol)+ ", VAT: " + vat);
            }
            }
        
            //accountReference, accountName,  mandateAmount, mandateStatus,  


            }
            
        /*{
    	System.out.println("Invoking retrieveBatchStatus...");
    	String _retrieveBatchStatus_serviceKey = DEBIT_ORDER_SERVICE_KEY;
    	String _retrieveBatchStatus__return = port.retrieveBatchStatus(_retrieveBatchStatus_serviceKey);
    	System.out.println("retrieveBatchStatus.result=" + _retrieveBatchStatus__return);
    }
    {
        System.out.println("Invoking requestInterimMerchantStatement...");
        String _requestInterimMerchantStatement_serviceKey = ACCOUNT_SERVICE_KEY;
        String _requestInterimMerchantStatement__return = port.requestInterimMerchantStatement(_requestInterimMerchantStatement_serviceKey);
        System.out.println("requestInterimMerchantStatement.result=\n" + _requestInterimMerchantStatement__return);
    }*/        
   
        
        
        /*{
            System.out.println("Invoking requestCombinedUploadReportForDate...");
            String _requestCombinedUploadReportForDate_serviceKey = DEBIT_ORDER_SERVICE_KEY;
            String _requestCombinedUploadReportForDate_date = "20251231";
            String _requestCombinedUploadReportForDate__return = port.requestCombinedUploadReportForDate(_requestCombinedUploadReportForDate_serviceKey, _requestCombinedUploadReportForDate_date);
            System.out.println("requestCombinedUploadReportForDate.result=\n" + _requestCombinedUploadReportForDate__return);
         }         

         {
        	System.out.println("Invoking retrieveUnauthorisedBatches...");
        	String _retrieveUnauthorisedBatches_serviceKey = "_retrieveUnauthorisedBatches_serviceKey-510471104";
        	String _retrieveUnauthorisedBatches__return = port.retrieveUnauthorisedBatches(_retrieveUnauthorisedBatches_serviceKey);
        	System.out.println("retrieveUnauthorisedBatches.result=" + _retrieveUnauthorisedBatches__return);


        }
        {
        	System.out.println("Invoking accountFundsRelease...");
        	String _accountFundsRelease_serviceKey = "_accountFundsRelease_serviceKey-1431234277";
        	String _accountFundsRelease_date = "_accountFundsRelease_date-876773529";
        	Long _accountFundsRelease_amountInCents = Long.valueOf(8180688984070009840l);
        	String _accountFundsRelease__return = port.accountFundsRelease(_accountFundsRelease_serviceKey, _accountFundsRelease_date, _accountFundsRelease_amountInCents);
        	System.out.println("accountFundsRelease.result=" + _accountFundsRelease__return);

        }
        {
        	System.out.println("Invoking retrieveTransactionTypes...");
        	String _retrieveTransactionTypes_serviceKey = "_retrieveTransactionTypes_serviceKey-2063699689";
        	String _retrieveTransactionTypes_pollingId = "_retrieveTransactionTypes_pollingId-2073348520";
        	String _retrieveTransactionTypes__return = port.retrieveTransactionTypes(_retrieveTransactionTypes_serviceKey, _retrieveTransactionTypes_pollingId);
        	System.out.println("retrieveTransactionTypes.result=" + _retrieveTransactionTypes__return);

        }
        {
        	System.out.println("Invoking requestTransactionTypes...");
        	String _requestTransactionTypes_serviceKey = "_requestTransactionTypes_serviceKey-1769622222";
        	String _requestTransactionTypes__return = port.requestTransactionTypes(_requestTransactionTypes_serviceKey);
        	System.out.println("requestTransactionTypes.result=" + _requestTransactionTypes__return);

        }
        {
        	System.out.println("Invoking retrieveProofOfPayment...");
        	String _retrieveProofOfPayment_serviceKey = "_retrieveProofOfPayment_serviceKey-250219422";
        	Integer _retrieveProofOfPayment_transactionId = Integer.valueOf(902445027);
        	org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.RetrieveProofOfPaymentResponse _retrieveProofOfPayment__return = port.retrieveProofOfPayment(_retrieveProofOfPayment_serviceKey, _retrieveProofOfPayment_transactionId);
        	System.out.println("retrieveProofOfPayment.result=" + _retrieveProofOfPayment__return);
        }
        {
        	System.out.println("Invoking requestPresentationDate...");
        	String _requestPresentationDate_serviceKey = "_requestPresentationDate_serviceKey910230628";
        	String _requestPresentationDate_date = "_requestPresentationDate_date1722701935";
        	String _requestPresentationDate_instruction = "_requestPresentationDate_instruction951998964";
        	String _requestPresentationDate_forwardActionDate = "_requestPresentationDate_forwardActionDate-1184007489";
        	String _requestPresentationDate__return = port.requestPresentationDate(_requestPresentationDate_serviceKey, _requestPresentationDate_date, _requestPresentationDate_instruction, _requestPresentationDate_forwardActionDate);
        	System.out.println("requestPresentationDate.result=" + _requestPresentationDate__return);
        }
        {
        	System.out.println("Invoking retrieveSpecificBatchStatus...");
        	String _retrieveSpecificBatchStatus_serviceKey = "_retrieveSpecificBatchStatus_serviceKey-1567708833";
        	String _retrieveSpecificBatchStatus_batchName = "_retrieveSpecificBatchStatus_batchName-1362889560";
        	String _retrieveSpecificBatchStatus__return = port.retrieveSpecificBatchStatus(_retrieveSpecificBatchStatus_serviceKey, _retrieveSpecificBatchStatus_batchName);
        	System.out.println("retrieveSpecificBatchStatus.result=" + _retrieveSpecificBatchStatus__return);
        }
        {
        	System.out.println("Invoking accountServiceKeys...");
        	String _accountServiceKeys_methodKey = "_accountServiceKeys_methodKey398480784";
        	String _accountServiceKeys_accountNo = "_accountServiceKeys_accountNo-757075129";
        	Integer _accountServiceKeys_softwareVendorCode = Integer.valueOf(-1366945711);
        	com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring _accountServiceKeys__return = port.accountServiceKeys(_accountServiceKeys_methodKey, _accountServiceKeys_accountNo, _accountServiceKeys_softwareVendorCode);
        	System.out.println("accountServiceKeys.result=" + _accountServiceKeys__return);
        }
        {
        System.out.println("Invoking addMandate...");
        String _addMandate_serviceKey = "_addMandate_serviceKey424756805";
        String _addMandate_accountReference = "_addMandate_accountReference-1686299891";
        String _addMandate_mandateName = "_addMandate_mandateName274753545";
        java.math.BigDecimal _addMandate_mandateAmount = new java.math.BigDecimal("441746912412878111.8203524613604769192");
        Boolean _addMandate_isConsumer = Boolean.valueOf(false);
        String _addMandate_firstName = "_addMandate_firstName-544399242";
        String _addMandate_surname = "_addMandate_surname1840683974";
        String _addMandate_tradingName = "_addMandate_tradingName709406047";
        String _addMandate_registrationNumber = "_addMandate_registrationNumber-131570592";
        String _addMandate_registeredName = "_addMandate_registeredName-1939405273";
        String _addMandate_mobileNumber = "_addMandate_mobileNumber685968989";
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsMandateDebitFrequency _addMandate_debitFrequency = org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsMandateDebitFrequency.ANNUALLY;
        Integer _addMandate_commencementMonth = Integer.valueOf(322094172);
        String _addMandate_commencementDay = "_addMandate_commencementDay237742366";
        String _addMandate_agreementDate = "_addMandate_agreementDate-220481007";
        String _addMandate_agreementReferenceNumber = "_addMandate_agreementReferenceNumber-1699215682";
        Integer _addMandate_cancellationNoticePeriod = Integer.valueOf(-1692005423);
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsMandatePublicHolidayOption _addMandate_publicHolidayOption = org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsMandatePublicHolidayOption.VERY_NEXT_ORDINARY_BUSINESS_DAY;
        String _addMandate_notes = "_addMandate_notes1760832508";
        String _addMandate_field1 = "_addMandate_field1537755104";
        String _addMandate_field2 = "_addMandate_field2-2145934059";
        String _addMandate_field3 = "_addMandate_field3-1203647155";
        String _addMandate_field4 = "_addMandate_field4770037184";
        String _addMandate_field5 = "_addMandate_field5-1656596936";
        String _addMandate_field6 = "_addMandate_field6-80940020";
        String _addMandate_field7 = "_addMandate_field71132875069";
        String _addMandate_field8 = "_addMandate_field82127505320";
        String _addMandate_field9 = "_addMandate_field9-743632357";
        Boolean _addMandate_allowVariableDebitAmounts = Boolean.valueOf(true);
        Integer _addMandate_bankDetailType = Integer.valueOf(-377057399);
        String _addMandate_bankAccountName = "_addMandate_bankAccountName-49829619";
        String _addMandate_bankAccountNumber = "_addMandate_bankAccountNumber1481429618";
        String _addMandate_branchCode = "_addMandate_branchCode-2116178089";
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsBankAccountType _addMandate_bankAccountType = org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsBankAccountType.SAVINGS;
        String _addMandate_creditCardToken = "_addMandate_creditCardToken2004005626";
        Integer _addMandate_creditCardType = Integer.valueOf(-421386615);
        Integer _addMandate_expiryMonth = Integer.valueOf(300291947);
        Integer _addMandate_expiryYear = Integer.valueOf(-1951612343);
        Boolean _addMandate_isIdNumber = Boolean.valueOf(false);
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsTitle _addMandate_title = org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsTitle.NOT_SET;
        String _addMandate_emailAddress = "_addMandate_emailAddress-1700681861";
        String _addMandate_phoneNumber = "_addMandate_phoneNumber-142545521";
        String _addMandate_dateOfBirth = "_addMandate_dateOfBirth-1792471886";
        String _addMandate_decemberDebitDay = "_addMandate_decemberDebitDay-1632779555";
        String _addMandate_debitMasterfileGroup = "_addMandate_debitMasterfileGroup-1019891781";
        String _addMandate_physicalAddressLine1 = "_addMandate_physicalAddressLine1642355835";
        String _addMandate_physicalAddressLine2 = "_addMandate_physicalAddressLine2-1713035694";
        String _addMandate_physicalAddressLine3 = "_addMandate_physicalAddressLine31576409507";
        String _addMandate_physicalSuburb = "_addMandate_physicalSuburb-877327803";
        String _addMandate_physicalCity = "_addMandate_physicalCity-496925659";
        String _addMandate_physicalProvince = "_addMandate_physicalProvince-1479081680";
        String _addMandate_physicalPostalCode = "_addMandate_physicalPostalCode827364768";
        Boolean _addMandate_mandateActive = Boolean.valueOf(true);
        Boolean _addMandate_requestAVS = Boolean.valueOf(false);
        String _addMandate_avsCheckNumber = "_addMandate_avsCheckNumber-1188264657";
        Boolean _addMandate_includeDebiCheck = Boolean.valueOf(true);
        String _addMandate_debiCheckMandateTemplateId = "_addMandate_debiCheckMandateTemplateId-925776377";
        java.math.BigDecimal _addMandate_debiCheckCollectionAmount = new java.math.BigDecimal("7532901501064870651.4576073574570406561");
        Boolean _addMandate_debiCheckFirstCollectionDiffers = Boolean.valueOf(true);
        String _addMandate_debiCheckFirstCollectionDate = "_addMandate_debiCheckFirstCollectionDate127444593";
        java.math.BigDecimal _addMandate_debiCheckFirstCollectionAmount = new java.math.BigDecimal("1558179552122738196.7368972155657823038");
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckOptionsCollectionFrequencyDayCodes _addMandate_debiCheckCollectionDayCode = org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckOptionsCollectionFrequencyDayCodes.ADHO_10;
        Boolean _addMandate_addToMasterFile = Boolean.valueOf(true);
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.AddMandateResponse _addMandate__return = port.addMandate(_addMandate_serviceKey, _addMandate_accountReference, _addMandate_mandateName, _addMandate_mandateAmount, _addMandate_isConsumer, _addMandate_firstName, _addMandate_surname, _addMandate_tradingName, _addMandate_registrationNumber, _addMandate_registeredName, _addMandate_mobileNumber, _addMandate_debitFrequency, _addMandate_commencementMonth, _addMandate_commencementDay, _addMandate_agreementDate, _addMandate_agreementReferenceNumber, _addMandate_cancellationNoticePeriod, _addMandate_publicHolidayOption, _addMandate_notes, _addMandate_field1, _addMandate_field2, _addMandate_field3, _addMandate_field4, _addMandate_field5, _addMandate_field6, _addMandate_field7, _addMandate_field8, _addMandate_field9, _addMandate_allowVariableDebitAmounts, _addMandate_bankDetailType, _addMandate_bankAccountName, _addMandate_bankAccountNumber, _addMandate_branchCode, _addMandate_bankAccountType, _addMandate_creditCardToken, _addMandate_creditCardType, _addMandate_expiryMonth, _addMandate_expiryYear, _addMandate_isIdNumber, _addMandate_title, _addMandate_emailAddress, _addMandate_phoneNumber, _addMandate_dateOfBirth, _addMandate_decemberDebitDay, _addMandate_debitMasterfileGroup, _addMandate_physicalAddressLine1, _addMandate_physicalAddressLine2, _addMandate_physicalAddressLine3, _addMandate_physicalSuburb, _addMandate_physicalCity, _addMandate_physicalProvince, _addMandate_physicalPostalCode, _addMandate_mandateActive, _addMandate_requestAVS, _addMandate_avsCheckNumber, _addMandate_includeDebiCheck, _addMandate_debiCheckMandateTemplateId, _addMandate_debiCheckCollectionAmount, _addMandate_debiCheckFirstCollectionDiffers, _addMandate_debiCheckFirstCollectionDate, _addMandate_debiCheckFirstCollectionAmount, _addMandate_debiCheckCollectionDayCode, _addMandate_addToMasterFile);
        System.out.println("addMandate.result=" + _addMandate__return);

        }
        {
        System.out.println("Invoking debiCheckCancelAuthentication...");
        String _debiCheckCancelAuthentication_serviceKey = "_debiCheckCancelAuthentication_serviceKey-1611211197";
        String _debiCheckCancelAuthentication_contractReference = "_debiCheckCancelAuthentication_contractReference52914117";
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckOptionsCancellationReasonCodes _debiCheckCancelAuthentication_reasonCode = org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckOptionsCancellationReasonCodes.AGNT;
        String _debiCheckCancelAuthentication__return = port.debiCheckCancelAuthentication(_debiCheckCancelAuthentication_serviceKey, _debiCheckCancelAuthentication_contractReference, _debiCheckCancelAuthentication_reasonCode);
        System.out.println("debiCheckCancelAuthentication.result=" + _debiCheckCancelAuthentication__return);

        }
        {
        System.out.println("Invoking getAvailableBalance...");
        String _getAvailableBalance_serviceKey = "_getAvailableBalance_serviceKey1438457671";
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.GetAvailableBalanceResponse _getAvailableBalance__return = port.getAvailableBalance(_getAvailableBalance_serviceKey);
        System.out.println("getAvailableBalance.result=" + _getAvailableBalance__return);


        }
        {
        System.out.println("Invoking retrieveBatchStatusByDate...");
        String _retrieveBatchStatusByDate_serviceKey = "_retrieveBatchStatusByDate_serviceKey169679034";
        String _retrieveBatchStatusByDate_startDate = "_retrieveBatchStatusByDate_startDate-1280601530";
        String _retrieveBatchStatusByDate_endDate = "_retrieveBatchStatusByDate_endDate-1309596493";
        String _retrieveBatchStatusByDate__return = port.retrieveBatchStatusByDate(_retrieveBatchStatusByDate_serviceKey, _retrieveBatchStatusByDate_startDate, _retrieveBatchStatusByDate_endDate);
        System.out.println("retrieveBatchStatusByDate.result=" + _retrieveBatchStatusByDate__return);


        }
       
        {
        System.out.println("Invoking requestAVSReport...");
        String _requestAVSReport_serviceKey = "_requestAVSReport_serviceKey-2013207493";
        String _requestAVSReport_fileToken = "_requestAVSReport_fileToken497230508";
        String _requestAVSReport__return = port.requestAVSReport(_requestAVSReport_serviceKey, _requestAVSReport_fileToken);
        System.out.println("requestAVSReport.result=" + _requestAVSReport__return);


        }
        {
        System.out.println("Invoking requestPayNowInvoice...");
        String _requestPayNowInvoice_serviceKey = "_requestPayNowInvoice_serviceKey-26338179";
        String _requestPayNowInvoice_fileToken = "_requestPayNowInvoice_fileToken-1486178384";
        String _requestPayNowInvoice__return = port.requestPayNowInvoice(_requestPayNowInvoice_serviceKey, _requestPayNowInvoice_fileToken);
        System.out.println("requestPayNowInvoice.result=" + _requestPayNowInvoice__return);


        }
        {
        System.out.println("Invoking getPaymentLimits...");
        String _getPaymentLimits_serviceKey = "_getPaymentLimits_serviceKey-14184443";
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.LimitResponse _getPaymentLimits__return = port.getPaymentLimits(_getPaymentLimits_serviceKey);
        System.out.println("getPaymentLimits.result=" + _getPaymentLimits__return);


        }
        {
        System.out.println("Invoking debiCheckRetrieveMandateTemplateDetail...");
        String _debiCheckRetrieveMandateTemplateDetail_serviceKey = "_debiCheckRetrieveMandateTemplateDetail_serviceKey1239654026";
        String _debiCheckRetrieveMandateTemplateDetail_debiCheckMandateTemplateId = "_debiCheckRetrieveMandateTemplateDetail_debiCheckMandateTemplateId1537319058";
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckMandateTemplateDetail _debiCheckRetrieveMandateTemplateDetail__return = port.debiCheckRetrieveMandateTemplateDetail(_debiCheckRetrieveMandateTemplateDetail_serviceKey, _debiCheckRetrieveMandateTemplateDetail_debiCheckMandateTemplateId);
        System.out.println("debiCheckRetrieveMandateTemplateDetail.result=" + _debiCheckRetrieveMandateTemplateDetail__return);


        }
        {
        System.out.println("Invoking debiCheckAuthenticate...");
        String _debiCheckAuthenticate_serviceKey = "_debiCheckAuthenticate_serviceKey926255146";
        String _debiCheckAuthenticate_accountReference = "_debiCheckAuthenticate_accountReference-850117432";
        String _debiCheckAuthenticate_debiCheckMandateTemplateId = "_debiCheckAuthenticate_debiCheckMandateTemplateId-956098601";
        Boolean _debiCheckAuthenticate_isIdNumber = Boolean.valueOf(true);
        String _debiCheckAuthenticate_debtorIdentification = "_debiCheckAuthenticate_debtorIdentification-589092066";
        String _debiCheckAuthenticate_accountName = "_debiCheckAuthenticate_accountName-1604328302";
        String _debiCheckAuthenticate_bankAccountName = "_debiCheckAuthenticate_bankAccountName-432352928";
        String _debiCheckAuthenticate_branchCode = "_debiCheckAuthenticate_branchCode623489958";
        String _debiCheckAuthenticate_bankAccountNumber = "_debiCheckAuthenticate_bankAccountNumber-193237810";
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsBankAccountType _debiCheckAuthenticate_bankAccountType = org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsBankAccountType.CURRENT;
        String _debiCheckAuthenticate_mobileNumber = "_debiCheckAuthenticate_mobileNumber-269238336";
        String _debiCheckAuthenticate_emailAddress = "_debiCheckAuthenticate_emailAddress-1300805768";
        java.math.BigDecimal _debiCheckAuthenticate_collectionAmount = new java.math.BigDecimal("-1657266583933339481.2416940725528870241");
        Boolean _debiCheckAuthenticate_firstCollectionDiffers = Boolean.valueOf(false);
        java.math.BigDecimal _debiCheckAuthenticate_firstCollectionAmount = new java.math.BigDecimal("457896457053931199.377961021090842065");
        String _debiCheckAuthenticate_firstCollectionDate = "_debiCheckAuthenticate_firstCollectionDate448235042";
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckOptionsCollectionFrequencyDayCodes _debiCheckAuthenticate_collectionDayCode = org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckOptionsCollectionFrequencyDayCodes.MIAN_02;
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckAuthenticateResponse _debiCheckAuthenticate__return = port.debiCheckAuthenticate(_debiCheckAuthenticate_serviceKey, _debiCheckAuthenticate_accountReference, _debiCheckAuthenticate_debiCheckMandateTemplateId, _debiCheckAuthenticate_isIdNumber, _debiCheckAuthenticate_debtorIdentification, _debiCheckAuthenticate_accountName, _debiCheckAuthenticate_bankAccountName, _debiCheckAuthenticate_branchCode, _debiCheckAuthenticate_bankAccountNumber, _debiCheckAuthenticate_bankAccountType, _debiCheckAuthenticate_mobileNumber, _debiCheckAuthenticate_emailAddress, _debiCheckAuthenticate_collectionAmount, _debiCheckAuthenticate_firstCollectionDiffers, _debiCheckAuthenticate_firstCollectionAmount, _debiCheckAuthenticate_firstCollectionDate, _debiCheckAuthenticate_collectionDayCode);
        System.out.println("debiCheckAuthenticate.result=" + _debiCheckAuthenticate__return);


        }
        {
        System.out.println("Invoking retrieveBlockedAccounts...");
        String _retrieveBlockedAccounts_serviceKey = "_retrieveBlockedAccounts_serviceKey-1335724329";
        String _retrieveBlockedAccounts_startDate = "_retrieveBlockedAccounts_startDate-1602053009";
        String _retrieveBlockedAccounts_endDate = "_retrieveBlockedAccounts_endDate-1352252586";
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.RetrieveBlockedAccountsResponse _retrieveBlockedAccounts__return = port.retrieveBlockedAccounts(_retrieveBlockedAccounts_serviceKey, _retrieveBlockedAccounts_startDate, _retrieveBlockedAccounts_endDate);
        System.out.println("retrieveBlockedAccounts.result=" + _retrieveBlockedAccounts__return);


        }*/
        
        /*{
        System.out.println("Invoking debiCheckAuthenticationCurrentStatus...");
        String _debiCheckAuthenticationCurrentStatus_serviceKey = "_debiCheckAuthenticationCurrentStatus_serviceKey-215895856";
        String _debiCheckAuthenticationCurrentStatus_contractReference = "_debiCheckAuthenticationCurrentStatus_contractReference-294283132";
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckAuthenticationCurrentStatusResponse _debiCheckAuthenticationCurrentStatus__return = port.debiCheckAuthenticationCurrentStatus(_debiCheckAuthenticationCurrentStatus_serviceKey, _debiCheckAuthenticationCurrentStatus_contractReference);
        System.out.println("debiCheckAuthenticationCurrentStatus.result=" + _debiCheckAuthenticationCurrentStatus__return);


        }
        {
        System.out.println("Invoking debiCheckAmendAuthentication...");
        String _debiCheckAmendAuthentication_serviceKey = "_debiCheckAmendAuthentication_serviceKey-673018874";
        String _debiCheckAmendAuthentication_contractReference = "_debiCheckAmendAuthentication_contractReference570416623";
        Long _debiCheckAmendAuthentication_collectionAmountInCents = Long.valueOf(1559834784871200019l);
        Long _debiCheckAmendAuthentication_maximumCollectionAmountInCents = Long.valueOf(5248784624317264643l);
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.DebiCheckAmendmentResponse _debiCheckAmendAuthentication__return = port.debiCheckAmendAuthentication(_debiCheckAmendAuthentication_serviceKey, _debiCheckAmendAuthentication_contractReference, _debiCheckAmendAuthentication_collectionAmountInCents, _debiCheckAmendAuthentication_maximumCollectionAmountInCents);
        System.out.println("debiCheckAmendAuthentication.result=" + _debiCheckAmendAuthentication__return);

        }
       
        {
        System.out.println("Invoking getDebitLimits...");
        String _getDebitLimits_serviceKey = "_getDebitLimits_serviceKey464064161";
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.LimitResponse _getDebitLimits__return = port.getDebitLimits(_getDebitLimits_serviceKey);
        System.out.println("getDebitLimits.result=" + _getDebitLimits__return);

        }
        {
        System.out.println("Invoking requestCreditDataReport...");
        String _requestCreditDataReport_serviceKey = "_requestCreditDataReport_serviceKey-1797050807";
        String _requestCreditDataReport_fileToken = "_requestCreditDataReport_fileToken-1483705824";
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring _requestCreditDataReport__return = port.requestCreditDataReport(_requestCreditDataReport_serviceKey, _requestCreditDataReport_fileToken);
        System.out.println("requestCreditDataReport.result=" + _requestCreditDataReport__return);

        }
        {
        System.out.println("Invoking requestBatchAuthorise...");
        String _requestBatchAuthorise_serviceKey = "_requestBatchAuthorise_serviceKey-1459172984";
        String _requestBatchAuthorise_batchIndicator = "_requestBatchAuthorise_batchIndicator-1356407691";
        Boolean _requestBatchAuthorise_sendEmail = Boolean.valueOf(false);
        String _requestBatchAuthorise_fromName = "_requestBatchAuthorise_fromName1330194221";
        String _requestBatchAuthorise_fromAddress = "_requestBatchAuthorise_fromAddress1954039102";
        Boolean _requestBatchAuthorise_sendSMS = Boolean.valueOf(false);
        Boolean _requestBatchAuthorise_releaseFunds = Boolean.valueOf(true);
        Boolean _requestBatchAuthorise_bankTransfer = Boolean.valueOf(true);
        String _requestBatchAuthorise__return = port.requestBatchAuthorise(_requestBatchAuthorise_serviceKey, _requestBatchAuthorise_batchIndicator, _requestBatchAuthorise_sendEmail, _requestBatchAuthorise_fromName, _requestBatchAuthorise_fromAddress, _requestBatchAuthorise_sendSMS, _requestBatchAuthorise_releaseFunds, _requestBatchAuthorise_bankTransfer);
        System.out.println("requestBatchAuthorise.result=" + _requestBatchAuthorise__return);


        }
        {
        System.out.println("Invoking requestDebitBatchUnauthorised...");
        String _requestDebitBatchUnauthorised_serviceKey = "_requestDebitBatchUnauthorised_serviceKey1727575935";
        String _requestDebitBatchUnauthorised_date = "_requestDebitBatchUnauthorised_date-1067731871";
        String _requestDebitBatchUnauthorised__return = port.requestDebitBatchUnauthorised(_requestDebitBatchUnauthorised_serviceKey, _requestDebitBatchUnauthorised_date);
        System.out.println("requestDebitBatchUnauthorised.result=" + _requestDebitBatchUnauthorised__return);


        }*/
        
        
        /*        {
        System.out.println("Invoking legacyCompactBatchFileUpload...");
        String _legacyCompactBatchFileUpload_userName = "_legacyCompactBatchFileUpload_userName-1689437403";
        String _legacyCompactBatchFileUpload_password = "_legacyCompactBatchFileUpload_password-1821236650";
        String _legacyCompactBatchFileUpload_pin = "_legacyCompactBatchFileUpload_pin1628632873";
        String _legacyCompactBatchFileUpload_file = "_legacyCompactBatchFileUpload_file-1407263024";
        String _legacyCompactBatchFileUpload_processAsLegacy = "_legacyCompactBatchFileUpload_processAsLegacy1557216085";
        String _legacyCompactBatchFileUpload__return = port.legacyCompactBatchFileUpload(_legacyCompactBatchFileUpload_userName, _legacyCompactBatchFileUpload_password, _legacyCompactBatchFileUpload_pin, _legacyCompactBatchFileUpload_file, _legacyCompactBatchFileUpload_processAsLegacy);
        System.out.println("legacyCompactBatchFileUpload.result=" + _legacyCompactBatchFileUpload__return);


        }
        {
        System.out.println("Invoking legacyBatchFileUpload...");
        String _legacyBatchFileUpload_userName = "_legacyBatchFileUpload_userName-1314226514";
        String _legacyBatchFileUpload_password = "_legacyBatchFileUpload_password261717685";
        String _legacyBatchFileUpload_pin = "_legacyBatchFileUpload_pin-307288708";
        String _legacyBatchFileUpload_file = "_legacyBatchFileUpload_file-1349191488";
        String _legacyBatchFileUpload_processAsLegacy = "_legacyBatchFileUpload_processAsLegacy776410003";
        String _legacyBatchFileUpload__return = port.legacyBatchFileUpload(_legacyBatchFileUpload_userName, _legacyBatchFileUpload_password, _legacyBatchFileUpload_pin, _legacyBatchFileUpload_file, _legacyBatchFileUpload_processAsLegacy);
        System.out.println("legacyBatchFileUpload.result=" + _legacyBatchFileUpload__return);


        }
        {
        System.out.println("Invoking avsRealtimeQuery...");
        String _avsRealtimeQuery_serviceKey = "_avsRealtimeQuery_serviceKey-1666151782";
        String _avsRealtimeQuery_accountReference = "_avsRealtimeQuery_accountReference2086392596";
        String _avsRealtimeQuery_extra1 = "_avsRealtimeQuery_extra1-1109929580";
        String _avsRealtimeQuery_extra2 = "_avsRealtimeQuery_extra2-749891843";
        String _avsRealtimeQuery_extra3 = "_avsRealtimeQuery_extra3-1478163797";
        String _avsRealtimeQuery_bankAccountNumber = "_avsRealtimeQuery_bankAccountNumber1665695447";
        String _avsRealtimeQuery_branchCode = "_avsRealtimeQuery_branchCode1576049362";
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsBankAccountType _avsRealtimeQuery_bankAccountType = org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MandateOptionsBankAccountType.SAVINGS;
        String _avsRealtimeQuery_enquiryName = "_avsRealtimeQuery_enquiryName497014346";
        String _avsRealtimeQuery_initials = "_avsRealtimeQuery_initials-1464548077";
        String _avsRealtimeQuery_idNumber = "_avsRealtimeQuery_idNumber1595461973";
        Boolean _avsRealtimeQuery_isIdNumber = Boolean.valueOf(true);
        String _avsRealtimeQuery_phoneNumber = "_avsRealtimeQuery_phoneNumber-672710902";
        String _avsRealtimeQuery_email = "_avsRealtimeQuery_email156565246";
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.AVSRealtimeQueryResponse _avsRealtimeQuery__return = port.avsRealtimeQuery(_avsRealtimeQuery_serviceKey, _avsRealtimeQuery_accountReference, _avsRealtimeQuery_extra1, _avsRealtimeQuery_extra2, _avsRealtimeQuery_extra3, _avsRealtimeQuery_bankAccountNumber, _avsRealtimeQuery_branchCode, _avsRealtimeQuery_bankAccountType, _avsRealtimeQuery_enquiryName, _avsRealtimeQuery_initials, _avsRealtimeQuery_idNumber, _avsRealtimeQuery_isIdNumber, _avsRealtimeQuery_phoneNumber, _avsRealtimeQuery_email);
        System.out.println("avsRealtimeQuery.result=" + _avsRealtimeQuery__return);


        }
        
        {
        System.out.println("Invoking requestFileUploadReport...");
        String _requestFileUploadReport_serviceKey = "_requestFileUploadReport_serviceKey-1289811563";
        String _requestFileUploadReport_fileToken = "_requestFileUploadReport_fileToken2044601286";
        String _requestFileUploadReport__return = port.requestFileUploadReport(_requestFileUploadReport_serviceKey, _requestFileUploadReport_fileToken);
        System.out.println("requestFileUploadReport.result=" + _requestFileUploadReport__return);


        }
        {
        System.out.println("Invoking retrieveMandatePDF...");
        String _retrieveMandatePDF_serviceKey = "_retrieveMandatePDF_serviceKey939212961";
        String _retrieveMandatePDF_fileToken = "_retrieveMandatePDF_fileToken1438884451";
        String _retrieveMandatePDF__return = port.retrieveMandatePDF(_retrieveMandatePDF_serviceKey, _retrieveMandatePDF_fileToken);
        System.out.println("retrieveMandatePDF.result=" + _retrieveMandatePDF__return);


        }
        {
        System.out.println("Invoking accountFundsTransfer...");
        String _accountFundsTransfer_serviceKey = "_accountFundsTransfer_serviceKey-854980400";
        String _accountFundsTransfer_toAccountNumber = "_accountFundsTransfer_toAccountNumber-1522129179";
        String _accountFundsTransfer_beneficiaryReference = "_accountFundsTransfer_beneficiaryReference-559188228";
        Long _accountFundsTransfer_amountInCents = Long.valueOf(3033271543133968188l);
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.AccountFundsTransferResponse _accountFundsTransfer__return = port.accountFundsTransfer(_accountFundsTransfer_serviceKey, _accountFundsTransfer_toAccountNumber, _accountFundsTransfer_beneficiaryReference, _accountFundsTransfer_amountInCents);
        System.out.println("accountFundsTransfer.result=" + _accountFundsTransfer__return);


        }
        {
        System.out.println("Invoking requestActionDate...");
        String _requestActionDate_serviceKey = "_requestActionDate_serviceKey1954244538";
        String _requestActionDate_date = "_requestActionDate_date-1279774331";
        String _requestActionDate_instruction = "_requestActionDate_instruction1248322674";
        String _requestActionDate_forwardActionDate = "_requestActionDate_forwardActionDate-1143584097";
        String _requestActionDate__return = port.requestActionDate(_requestActionDate_serviceKey, _requestActionDate_date, _requestActionDate_instruction, _requestActionDate_forwardActionDate);
        System.out.println("requestActionDate.result=" + _requestActionDate__return);


        }
        
        {
        System.out.println("Invoking merchantStatementSourceStatus...");
        String _merchantStatementSourceStatus_serviceKey = "_merchantStatementSourceStatus_serviceKey-500200371";
        String _merchantStatementSourceStatus_date = "_merchantStatementSourceStatus_date670343199";
        org.datacontract.schemas._2004._07.nc_dg_tms_c_wcf.MerchantStatementSourceStatusResponse _merchantStatementSourceStatus__return = port.merchantStatementSourceStatus(_merchantStatementSourceStatus_serviceKey, _merchantStatementSourceStatus_date);
        System.out.println("merchantStatementSourceStatus.result=" + _merchantStatementSourceStatus__return);


        }
        {
        System.out.println("Invoking isValidServiceKey...");
        String _isValidServiceKey_methodKey = "_isValidServiceKey_methodKey-1399767582";
        String _isValidServiceKey_serviceKey = "_isValidServiceKey_serviceKey-1672007278";
        String _isValidServiceKey_instructionCode = "_isValidServiceKey_instructionCode-643383661";
        Integer _isValidServiceKey_sofwareVendorCode = Integer.valueOf(-336604655);
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring _isValidServiceKey__return = port.isValidServiceKey(_isValidServiceKey_methodKey, _isValidServiceKey_serviceKey, _isValidServiceKey_instructionCode, _isValidServiceKey_sofwareVendorCode);
        System.out.println("isValidServiceKey.result=" + _isValidServiceKey__return);


        }
        {
        System.out.println("Invoking batchFileUpload...");
        String _batchFileUpload_serviceKey = SERVICE_KEY;
        String _batchFileUpload_file = "_batchFileUpload_file-2130984344";
        String _batchFileUpload__return = port.batchFileUpload(_batchFileUpload_serviceKey, _batchFileUpload_file);
        System.out.println("batchFileUpload.result=" + _batchFileUpload__return);


        }*/
        System.exit(0);
    }
    
    public INIWSNIF getPort() {
    	return port;
    }

    
    public static String getSoapDate(String inputDateString, String inPutFormat){
    	// Define the format of the input string
        DateTimeFormatter inputFormatter = DateTimeFormatter.ofPattern(/*"dd MMM yyyy"*/inPutFormat);
        // Parse the input string into a LocalDate object
        LocalDate date = LocalDate.parse(inputDateString, inputFormatter);
        // Define the desired output format
        DateTimeFormatter outputFormatter = DateTimeFormatter.ofPattern("yyyyMMdd");
        // Format the LocalDate object into the desired string format
        String outputDateString = date.format(outputFormatter);
        
        return outputDateString;

    }
    
    public static String getSymbolDescription(String plusMinus){
    	String symolDescription=null;
    	if("+".equals(plusMinus)) {
    		symolDescription="credit";
    	
    	} else {
    		symolDescription="debit";
    	}
    	
    	return symolDescription;
    }

}
